[NAYB-37] feat: 관리자는 이벤트를 생성할 수 있다.
prgrms-be-devcourse/BE-04-NaBMart pull request #19
Opened 2023-09-01 07:51 UTC by funnysunny08

### ⛏ 작업 사항
- 이벤트 생성 API 

### 📝 작업 요약
- 이벤트 생성을 위한 `EventController`, `EventService`, `EventRepository` 추가
- `RegisterEventRequest`, `RegisterEventCommand` dto 추가

### 💡 관련 이슈
[NAYB-37] (https://naybmart.atlassian.net/browse/NAYB-37?atlOrigin=eyJpIjoiMDRlM2U5OWY3ODZhNGM4OTk3ZWQwZTJlODhhODkxMWUiLCJwIjoiaiJ9)

### 궁금한 점..🥲
- 노션을 열심히 읽긴 했지만 convention이 제대로 지켜진 건지 궁금합니다!.!
- `EventController`에서 response header를 이런 식으로 넘기는 게 맞는지 궁금합니다!.!
- 이벤트 생성을 관리자만이 할 수 있는데 해당 처리는 security 쪽에서 하는 게 맞을까요?!
- 테스트는 작성해 본 적이 없어 다른 분들 올리시면 참고해서 추가하겠습니당!

2023-09-01 07:58 UTC, hseong3243 reviewed
리뷰 남겼습니다. 확인 부탁드려요!

2023-09-01 07:58 UTC, hseong3243 commented on src/main/java/com/prgrms/nabmart/domain/event/dto/RegisterEventCommand.java
> +package com.prgrms.nabmart.domain.event.dto;
패키지 컨벤션 한 번 확인해주세요! 컨트롤러 <-> 서비스 계층에서 사용하는 dto는 해당 패키지에 `request` 패키지를 만들어서 둬주시면 됩니다!

2023-09-01 07:58 UTC, hseong3243 commented on src/main/java/com/prgrms/nabmart/domain/event/dto/RegisterEventRequest.java
> +package com.prgrms.nabmart.domain.event.dto;
요것도 클라이언트 <-> 컨트롤러 dto는 controller 패키지에 `request` 패키지를 따로 만들어주세요!

2023-09-01 08:07 UTC, Seongju-Lee requested changes
- 패키지 컨벤션
https://www.notion.so/backend-devcourse/Package-Convention-2e8bd476aabb4a48b20b4176b443dccd

dto 변환 관련해서 해당 컨벤션 확인해주시면 좋을 것 같습니다!!!

2023-09-01 08:08 UTC, bjo6300 reviewed
고생하셨습니다! 코드 구현하면서 컨벤션 맞춰가면 될거 같아요!

2023-09-01 08:08 UTC, bjo6300 commented on src/main/java/com/prgrms/nabmart/domain/event/controller/EventController.java
> +        response.setHeader("Location", "/v1/events/" + eventId);
```
URI location = URI.create(BASE_URL + cartItemId);

return ResponseEntity.created(location).build();
```
전 status 코드랑 location 한번에 처리 가능해서 이렇게 했어요! 스크럼 때 코드 컨벤션 이야기 나눠봐요~

![image](https://github.com/prgrms-be-devcourse/BE-04-NaBMart/assets/70627982/21090320-a4da-4530-98ff-cdf0cba786d0)

2023-09-01 08:08 UTC, bjo6300 commented on src/main/java/com/prgrms/nabmart/domain/event/dto/RegisterEventRequest.java
> +    @NotNull String description
String 값은 @NotBlank 어떠신가요?? 예외메세지도 적어주시면 좋을 것 같아요!
https://sanghye.tistory.com/36

2023-09-01 08:08 UTC, bjo6300 commented on src/main/java/com/prgrms/nabmart/domain/event/dto/RegisterEventCommand.java
> +}
코드 컨벤션에 따르면 command 파일은 `service/request ` 내부에 있어요~

2023-09-01 08:08 UTC, bjo6300 commented on src/main/java/com/prgrms/nabmart/domain/event/dto/RegisterEventRequest.java
> +}
코드 컨벤션에 따르면 request 파일은 `controller/request`  내부에 있어요~

2023-09-01 08:19 UTC, pushedrumex requested changes

2023-09-01 08:19 UTC, pushedrumex commented on src/main/java/com/prgrms/nabmart/domain/event/service/EventService.java
> +        Event event = new Event(registerEventCommand.title(), registerEventCommand.description());
전체적으로 `final`이 빠져있네요!(컨벤션)

```
- 필드에 붙인다.
- 매개변수에 붙인다.
- 유틸 클래스에 붙인다.
```

2023-09-02 16:29 UTC, hseong3243 approved these changes

2023-09-03 05:21 UTC, bjo6300 approved these changes

2023-09-03 05:26 UTC, bjo6300 commented on src/main/java/com/prgrms/nabmart/domain/event/domain/Event.java
> +        this.description = description;
title, description에 대한 검증이 필요해요 !
`코드컨벤션 2번 validation`

2023-09-03 05:26 UTC, bjo6300 commented on src/main/java/com/prgrms/nabmart/domain/event/service/request/RegisterEventCommand.java
> +    public static RegisterEventCommand from(String title, String description) {
정적 팩토리 메소드에 final 추가해주세요~
`코드 컨벤션 4번 final`

2023-09-03 07:02 UTC, pushedrumex approved these changes

2023-09-03 07:52 UTC, funnysunny08 commented on src/main/java/com/prgrms/nabmart/domain/event/domain/Event.java
> +        this.description = description;
넵 추가했습니당!

2023-09-03 07:52 UTC, funnysunny08 commented on src/main/java/com/prgrms/nabmart/domain/event/service/request/RegisterEventCommand.java
> +    public static RegisterEventCommand from(String title, String description) {
넵 추가했습니다!! 
감사합니당

2023-09-03 09:46 UTC, Seongju-Lee approved these changes

2023-09-03 15:10 UTC, merged